export default {
  // Fetch Member
  FETCH_MEMBER: 'FETCH_MEMBER',
  FETCH_MEMBER_START: 'FETCH_MEMBER_START',
  FETCH_MEMBER_FAILED: 'FETCH_MEMBER_FAILED',
  FETCH_MEMBER_FAILED_NETWORK: 'FETCH_MEMBER_FAILED_NETWORK',
  FETCH_MEMBER_FINISHED: 'FETCH_MEMBER_FINISHED',
  SET_MEMBER: 'SET_MEMBER',
  CLEAR_MEMBER: 'CLEAR_MEMBER',
  REFRESH_MEMBER_DATA: 'REFRESH_MEMBER_DATA',
  UPDATE_MEMBER_FIELDS: 'UPDATE_MEMBER_FIELDS',
};
