export default {
  SRV_DATA: 'SRV_DATA',
  HERO_DATA: 'HERO_DATA',
  // ==== SAGA ====
  SAGA_SRV_DATA: 'SAGA_SRV_DATA',
  SAGA_HERO_DATA: 'SAGA_HERO_DATA',
  SAGA_CARD_DATA_BY_ID: 'SAGA_CARD_DATA_BY_ID',
  CARD_DATA_BY_ID: 'CARD_DATA_BY_ID',
};
