export const LOGOUT_FINISHED = 'LOGOUT_FINISHED';

export default {
  // LOGIN
  LOGIN: 'LOGIN',
  LOGIN_START: 'LOGIN_START',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_FAILED_NETWORK: 'LOGIN_FAILED_NETWORK',
  LOGIN_FINISHED: 'LOGIN_FINISHED',
  // THIRD_PARTY
  USER_REGISTER_WITH_THIRD_PARTY: 'USER_REGISTER_WITH_THIRD_PARTY',
  // REGISTER
  REGISTER: 'REGISTER',
  REGISTER_START: 'REGISTER_START',
  REGISTER_FAILED: 'REGISTER_FAILED',
  REGISTER_FAILED_NETWORK: 'REGISTER_FAILED_NETWORK',
  REGISTER_FINISHED: 'REGISTER_FINISHED',
  // LOGOUT
  LOGOUT: 'LOGOUT',
  LOGOUT_FINISHED,
  // RESET_PASSWORD
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
  RESET_PASSWORD_FAILED_NETWORK: 'RESET_PASSWORD_FAILED_NETWORK',
  RESET_PASSWORD_FINISHED: 'RESET_PASSWORD_FINISHED',
  // FORM
  SET_AUTH_FORM: 'SET_AUTH_FORM',
  CLEAR_AUTH_FORM: 'CLEAR_AUTH_FORM',
  // PERSIST
  USER_PERSIST_FROM_STORAGE: 'USER_PERSIST_FROM_STORAGE',
  SET_LAST_USER_IN_STORE: 'SET_LAST_USER_IN_STORE',
  CLEAN_LAST_USER: 'CLEAN_LAST_USER',
  // SET ON STORE
  SET_AUTH_PARAMETERS: 'SET_AUTH_PARAMETERS',
  SET_INIT_URL: 'SET_INIT_URL',
  SET_TOKEN_VALIDATIONS_STATUS: 'SET_TOKEN_VALIDATIONS_STATUS',
  ON_APP_LOAD_FINISHED: 'ON_APP_LOAD_FINISHED',
  // RUN THIS FROM SPLASH SCREEN
  ON_APP_LOAD: 'ON_APP_LOAD',
  // RUN THIS IF TOKEN FOUND IN STORG AND AFTER LOGIN/REGISTER
  AUTHORIZED: 'AUTHORIZED',
  // RUN WHEN USER OPEN THE APP AND TOKEN NOT FOUND
  UNAUTHORIZED: 'UNAUTHORIZED',
  // TOKEN
  IS_TOKEN_VALID: 'IS_TOKEN_VALID',
  // Cookies
  SET_USER_FROM_COOKIES: 'SET_USER_FROM_COOKIES'
};
